service: prs-github

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-1
  usagePlan: # Optional usage plan configuration
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100

environment:
  GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}

#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  post:
    handler: handler.post
    events:
      - http:
          path: post
          method: post
          cors: true